### ISSUE TITLE
Get RGBa from Color

### ISSUE THREAD

**Issue by d47081** [kurtlawrence/cansi#10]
Hello, 
I see that `Code` defined as `enum` - is any option to convert it into RGBa or HEX presentation with `cansi` API?
Something like [this](https://github.com/colored-rs/colored/blob/master/src/color.rs#L138)

Thanks!

**Comment by kurtlawrence** [comment]
It is definitely feasible, if you'd like to open a PR with the changes I can review

**Comment by d47081** [comment]
Well, if not exist yet, it would be nice to have some template model instead of hardcode values, I suppose

or those values strictly defined in specification?

**Comment by kurtlawrence** [comment]
It is up to the terminal to convert name to rgb value. We could provide some 'defaults' though.

TBH it is probably better handled in the client's code.

**Comment by d47081** [comment]
You're right, I forgot that [GTK constructor](https://docs.gtk.org/gdk4/struct.RGBA.html) require float 0-1 values so issue could be closed, thanks

Here is [implementation](https://github.com/YGGverse/Yoda/blob/master/src/app/browser/window/tab/item/page/content/text/gemini/reader/ansi.rs#L54) with 0-1 values instead of 0-255 in my case.
