### ISSUE TITLE
Intensity enum interpretation

### ISSUE THREAD

**Issue by d47081** [kurtlawrence/cansi#11]
Not sure I understand what is `Faint` means - it's `Italic` or something else? Please, explain

``` rust
pub enum Intensity {
    /// Normal intensity (no emphasis).
    Normal,
    /// Bold.
    Bold,
    /// Faint.
    Faint,
}
```

**Comment by kurtlawrence** [comment]
Faint means it uses a colour with less brightness.

See https://en.wikipedia.org/wiki/ANSI_escape_code#Select_Graphic_Rendition_parameters

**Comment by d47081** [comment]
Thank you!
