### ISSUE TITLE
A `String` in `categorise_text`

### ISSUE THREAD

**Issue by refaelsh** [kurtlawrence/cansi#5]
Please consider the following:
```rust
fn some_function() -> CategorisedSlices {
    let text_with_codes : String = .... 

    categorise_text(&text_with_codes)
}
```
The above produces the following error:
```rust
error[E0515]: cannot return value referencing local variable `text_with_codes`
  --> src/model/git_commander/git_commander.rs:28:9
   |
28 |         categorise_text(&text_with_codes)
   |         ^^^^^^^^^^^^^^^^----------------^
   |         |               |
   |         |               `text_with_codes` is borrowed here
   |         returns a value referencing data owned by the current function
```

I am not really sure its a bug in `cansi`. If `categorise_text` would accept `String` instead of `&str`, this error would not happen.

Please advise :-) I really need to return `CategorisedSlices` from my functions.

**Comment by kurtlawrence** [comment]
Hi @refaelsh.

Please take a look at [`categorise_text`](https://docs.rs/cansi/latest/cansi/fn.categorise_text.html) in the docs.
The lifetime of `CategorisedSlices` is tied to the input into the `categorise_text` function.

To make this compile, the input `String` must live for longer than the constructed `CategorisedSlices`.

To understand lifetimes further, take a look at the [chapter in the Rust book](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html).

**Comment by refaelsh** [comment]
I understand what you are saying. I know about life times (or at least I think I know).
But the only solution I can come up with is to make the `text_with_codes` variable a global and/or static - and I want to avoid this.
Can you please provide an example of how to use your crate in my case when I want to return `CategorisedSlices`?

Thank you in advance :-)

**Comment by kurtlawrence** [comment]
You won't be able to return `CategorisedSlices` referencing a locally scoped variable. I am not sure if you are a fully understanding lifetimes. The `CategorisedSlices` references `text_with_codes`, which gets dropped at the end of `some_function`. It is not possible for `CategorisedSlices` to be referencing this memory, since the memory would have been freed at this point.

As a very hacky work around, you could return your own structure which contains an owned copy of the text:
```rust
fn some_function() -> Vec<(String, CategorisedSlice<'static>) {
    let text_with_codes : String = .... 

    categorise_text(&text_with_codes)
        .into_iter()
        .map(|mut slice| {
            let text = slice.text.to_string();
            slice.text = "";
            (text, slice)
        })
        .collect::<Vec<_>>()
}
```

(I did not test if that would compile.)

**Comment by refaelsh** [comment]
I will go and try your solution. Thank you @kurtlawrence.
